### ISSUE TITLE
Error when trying to create mass action

### ISSUE THREAD

**Issue by pacheco25** [DouglasCAyers/sfdx-mass-action-scheduler#27]
Hi,

I get this error message when trying to create a new mass action:

"No CONTROLLER named js://dca_mass_action.strike_tooltip found".

Could someone help?

Regards

Pacheco

**Comment by DouglasCAyers** [comment]
Hi @pacheco25,

I haven't heard back from you so I'm assuming this issue is resolved? I'm closing the issue but if you're still having the same error, please provide screen shots and I'll re-open it.

Thanks,

Doug

**Comment by adambeal** [comment]
Hi Doug I just got this same errror and disabling lightning cache per instructions linked above did not help, nor did re-installing.  I am using enterprise edition sandbox and here is error:
No CONTROLLER named js://dca_mass_action.strike_tooltip found

Stack trace:
org.auraframework.throwable.quickfix.DefinitionNotFoundException: No CONTROLLER named js://dca_mass_action.strike_tooltip found
	at org.auraframework.impl.linker.AuraLinker.getHelper(AuraLinker.java:325)
	at org.auraframework.impl.linker.AuraLinker.linkDefinition(AuraLinker.java:174)
	at org.auraframework.impl.linker.AuraLinker.getDefinitionDuringLink(AuraLinker.java:197)
	at org.auraframework.impl.DefinitionServiceImpl.getDefinition(DefinitionServiceImpl.java:247)
	at org.auraframework.impl.compound.controller.CompoundControllerDefFactory.getDef(CompoundControllerDefFactory.java:74)
	at org.auraframework.impl.compound.controller.CompoundControllerDefFactory.getDef(CompoundControllerDefFactory.java:39)
	at org.auraframework.impl.system.NonCachingDefRegistryImpl.getDef(NonCachingDefRegistryImpl.java:63)
	at org.auraframework.impl.linker.AuraLinker.fillLinkingDefinition(AuraLinker.java:516)
	at org.auraframework.impl.linker.AuraLinker.getHelper(AuraLinker.java:314)
	at org.auraframework.impl.linker.AuraLinker.linkDefinition(AuraLinker.java:174)
	at org.auraframework.impl.DefinitionServiceImpl.compileDE(DefinitionServiceImpl.java:1061)
	at org.auraframework.impl.DefinitionServiceImpl.getDefinition(DefinitionServiceImpl.java:258)
	at org.auraframework.impl.system.DefDescriptorImpl.getDef(DefDescriptorImpl.java:339)
	at org.auraframework.impl.root.component.BaseComponentDefImpl.getControllerDef(BaseComponentDefImpl.java:893)
	at org.auraframework.impl.root.component.BaseComponentDefImpl.serialize(BaseComponentDefImpl.java:1067)
	at org.auraframework.impl.root.component.ComponentDefImpl.serialize(ComponentDefImpl.java:127)
	at org.auraframework.util.json.JsonSerializers$OldSerializer.serialize(JsonSerializers.java:148)
	at org.auraframework.util.json.JsonSerializers$OldSerializer.serialize(JsonSerializers.java:126)
	at org.auraframework.util.json.JsonEncoder.writeValue(JsonEncoder.java:570)
	at org.auraframework.util.json.JsonEncoder.writeArrayEntry(JsonEncoder.java:686)
	at org.auraframework.util.json.JsonEncoder.writeArray(JsonEncoder.java:669)
	at org.auraframework.util.json.JsonSerializers$CollectionSerializer.serialize(JsonSerializers.java:173)
	at org.auraframework.util.json.JsonSerializers$CollectionSerializer.serialize(JsonSerializers.java:165)
	at org.auraframework.util.json.JsonEncoder.writeValue(JsonEncoder.java:570)
	at org.auraframework.util.json.JsonEncoder.writeMapEntry(JsonEncoder.java:729)
	at org.auraframework.util.json.JsonEncoder.writeMapEntry(JsonEncoder.java:700)
	at org.auraframework.impl.context.AuraContextJsonSerializer.writeDefs(AuraContextJsonSerializer.java:79)
	at org.auraframework.impl.context.AuraContextJsonSerializer.serialize(AuraContextJsonSerializer.java:236)
	at org.auraframework.impl.context.AuraContextJsonSerializer.serialize(AuraContextJsonSerializer.java:89)
	at org.auraframework.impl.context.AuraContextJsonSerializer.serialize(AuraContextJsonSerializer.java:51)
	at org.auraframework.util.json.JsonEncoder.writeValue(JsonEncoder.java:570)
	at org.auraframework.util.json.JsonEncoder.writeMapEntry(JsonEncoder.java:729)
	at org.auraframework.util.json.JsonEncoder.writeMapEntry(JsonEncoder.java:700)
	at org.auraframework.impl.ServerServiceImpl.run(ServerServiceImpl.java:174)
	at org.auraframework.http.AuraServlet.handleActionRequest(AuraServlet.java:625)
	at org.auraframework.http.AuraServlet.doPost(AuraServlet.java:664)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty94.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1644)
	at system.filter.AuraDomainRedirectFilter.doFilter(AuraDomainRedirectFilter.java:81)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at aura.impl.http.SFDCAuraContextFilter.doFilter(SFDCAuraContextFilter.java:228)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at sfdc.commons.filters.useragent.CommonUserAgentRewriteFilter.doFilter(CommonUserAgentRewriteFilter.java:27)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at klein.filter.JettyStreamWriterAdaptorFilter.doFilter(JettyStreamWriterAdaptorFilter.java:114)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at sfdc.commons.filters.cookie.CookieCatalogFilter.doFilter(CookieCatalogFilter.java:68)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at sfdc.commons.filters.vulnerability.CommonVulnerabilityCheckFilter.doFilter(CommonVulnerabilityCheckFilter.java:68)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at system.filter.SeparateDomainRedirectFilter.doFilter(SeparateDomainRedirectFilter.java:139)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at core.dns.filter.CustomDomainMappingFilter.doFilter(CustomDomainMappingFilter.java:226)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at core.dns.filter.SiteRedirectMappingFilter.doFilter(SiteRedirectMappingFilter.java:119)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at core.dns.filter.BandwidthMeterFilter.doFilter(BandwidthMeterFilter.java:129)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at system.filter.OrgDomainFilter.doFilter(OrgDomainFilter.java:202)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at system.filter.StatsOnlyFilter.doFilter(StatsOnlyFilter.java:85)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at system.filter.RedirectFilter.doFilter(RedirectFilter.java:332)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at sfdc.commons.filters.modifyparam.ModifiableParameterFilter.doFilter(ModifiableParameterFilter.java:41)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at klein94.filter.MultiPartFilter.doFilter(MultiPartFilter.java:112)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at system.filter.BasePreGzipFilter.doFilter(BasePreGzipFilter.java:197)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at com.force.http.routing.RoutingFilter.doFilter(RoutingFilter.java:68)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at system.filter.InstanceRedirectFilter.doFilter(InstanceRedirectFilter.java:865)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at sfdc.commons.filters.routing.CommonRemoteAddrFilter.doFilter(CommonRemoteAddrFilter.java:80)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at system.filter.LegacyJSPFilter.doFilter(LegacyJSPFilter.java:218)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at routing.ios.IosRoutingFilter.doFilter(IosRoutingFilter.java:98)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at core.feeds.notification.tracking.ClickTrackingFilter.doFilter(ClickTrackingFilter.java:102)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at core.dns.filter.SitesRuntimeForwardingFilter.requestIsNotForSites(SitesRuntimeForwardingFilter.java:216)
	at core.dns.filter.SitesRuntimeForwardingFilter.doFilterInternal(SitesRuntimeForwardingFilter.java:444)
	at core.dns.filter.SitesRuntimeForwardingFilter.doFilter(SitesRuntimeForwardingFilter.java:255)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at sites.gateway.EdgeGatewayCachingFilter.doFilter(EdgeGatewayCachingFilter.java:36)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at routing.filter.LoadBalancerFilter.doFilter(LoadBalancerFilter.java:81)
	at routing.loadbalancer.SfdcLoadBalancerFilter.doFilter(SfdcLoadBalancerFilter.java:691)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at common.util.database.ZeroDowntimeSpinModeFilter.doFilter(ZeroDowntimeSpinModeFilter.java:45)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at system.orgdomain.OrgDomainLoadBalancerFilter.doFilter(OrgDomainLoadBalancerFilter.java:82)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at system.filter.MeshDistributedTracingFilter.doFilter(MeshDistributedTracingFilter.java:58)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at system.filter.MeshDynamicRequestRoutingFilter.doFilter(MeshDynamicRequestRoutingFilter.java:65)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at sfdc.commons.filters.context.CommonStackableContextWatchingFilter.doFilter(CommonStackableContextWatchingFilter.java:201)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at sfdc.commons.filters.context.CommonContextReleaseFilter.doFilter(CommonContextReleaseFilter.java:75)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at system.filter.SessionNeverEstablishedLogFilter.doFilter(SessionNeverEstablishedLogFilter.java:63)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at com.force.http.routing.RoutingFilter.doFilter(RoutingFilter.java:68)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at com.force.http.routing.RoutingFilter.handleFilter(RoutingFilter.java:117)
	at com.force.http.routing.RoutingFilter.doFilter(RoutingFilter.java:74)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at system.filter.Immediate404Filter.doFilter(Immediate404Filter.java:99)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at system.filter.HttpsRedirectFilter.doFilter(HttpsRedirectFilter.java:117)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at sfdc.commons.filters.security.CommonResponseHeaderFilter.doFilter(CommonResponseHeaderFilter.java:49)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at sfdc.commons.filters.headers.CommonJettyResponseHeadersCustomizerFilter.doFilter(CommonJettyResponseHeadersCustomizerFilter.java:28)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at sfdc.commons.filters.buffer.CommonResponseBufferSizeAdjusterFilter.doFilter(CommonResponseBufferSizeAdjusterFilter.java:33)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at klein94.filter.IncludableResponseWrapperFilter.doFilter(IncludableResponseWrapperFilter.java:38)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at system.filter.CookieProcessorFilter.doFilter(CookieProcessorFilter.java:148)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at sfdc.commons.filters.logging.CommonAccessLogFilter.doFilter(CommonAccessLogFilter.java:54)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at sfdc.commons.filters.context.CommonRequestIdFilter.doFilter(CommonRequestIdFilter.java:56)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at system.filter.RegulatorWaitTestFilter.doFilter(RegulatorWaitTestFilter.java:64)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at system.filter.RegulatorFilter.doFilter(RegulatorFilter.java:83)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at system.filter.RequestPathSecurityFilter.doFilter(RequestPathSecurityFilter.java:70)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at sfdc.commons.filters.encoding.CommonRequestEncodingFilter.doFilter(CommonRequestEncodingFilter.java:86)
	at system.filter.RequestEncodingFilter.doFilter(RequestEncodingFilter.java:35)
	at org.eclipse.jetty94.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at org.eclipse.jetty94.servlet.ServletHandler.doHandle(ServletHandler.java:546)
	at org.eclipse.jetty94.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty94.server.handler.gzip.GzipHandler.handle(GzipHandler.java:521)
	at klein94.handler.SfdcGzipHandler.handle(SfdcGzipHandler.java:43)
	at org.eclipse.jetty94.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty94.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty94.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty94.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty94.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty94.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty94.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at klein94.jetty94.RegexServletHandler.doScope(RegexServletHandler.java:171)
	at org.eclipse.jetty94.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty94.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty94.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty94.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty94.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
	at org.eclipse.jetty94.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty94.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)
	at org.eclipse.jetty94.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
	at org.eclipse.jetty94.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty94.server.Server.handle(Server.java:564)
	at org.eclipse.jetty94.server.HttpChannel.handle(HttpChannel.java:317)
	at org.eclipse.jetty94.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty94.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty94.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty94.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty94.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty94.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty94.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty94.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty94.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty94.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:760)
	at org.eclipse.jetty94.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:678)
	at java.lang.Thread.run(Thread.java:748)


I didn't get the error when testing the production version in my dev org, only the sandbox version. Can you advise?

**Comment by douglascayers** [comment]
Hi Adam, this may be related to known issues with sandboxes and managed packages as mentioned here: https://github.com/douglascayers/sfdx-mass-action-scheduler/issues/42#issuecomment-417154570

Especially since you say this works in Prod but not a sandbox.
